# Generated by Django 3.1.2 on 2022-02-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('trade_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('stock_symbol', models.CharField(max_length=255)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolio')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
