# Generated by Django 3.1.2 on 2022-02-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='api.portfolio'),
        ),
    ]
